name: Linting

on:
  push:
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:
    name: Markdown linting
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.1.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install markdownlinter-cli
        run: npm install markdownlint-cli

      - name: Lint all markdown files
        run: ./node_modules/.bin/markdownlint ./ --ignore node_modules --ignore v5
